version: '3'

services:
  grafana:
    image: "grafana/grafana:latest"
    links:
      - "leaderboard:leaderboard"
    ports:
      - "3000:3000"
    environment:
        - GF_INSTALL_PLUGINS=redis-datasource,grafana-simple-json-datasource
    depends_on:
      - leaderboard
  leaderboard:
    image: "maguec/grafanaleaderboard:latest"
    environment:
        - REDIS_SERVER=redis
        - REDIS_LEADERBOARD_SET=LeaderBoards
    ports:
      - "5000:5000"
